{% set name = "parallel_statistics" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/parallel_statistics/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e8dcde1681db8fa9ede789c45a7a863e02e2463cbf13b161c3016bde2644ca74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - numba  # technically optional but better to always have it

test:
  imports:
    - parallel_statistics

about:
  home: https://github.com/LSSTDESC/parallel_statistics
  summary: 'Parallel, incremental statistics using MPI in python'
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
